function [result] = iterative_analysis_understanding_stat_5algos(label)

switch label
    case 0
        result =4;    
    case 1
        result =4;
    case 2
        result =5;
	case 3
        result =4;
    case 4
        result =4;
    case 5
        result =3;
    case 6
        result =5;
    case 7
        result =5;
    case 8
        result =4;
    case 9
        result =5;
    case 10
        result =5;
    case 11
        result =1;
    case 12
        result =4;
    case 13
        result =4;
    case 14
        result =5;
    case 15
        result =4;
    case 16
        result =5;
    case 17
        result =4;
    case 18
        result =4;
    case 19
        result =5;
    case 20
        result =3;            
end 